// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/notif-onboarding/NotifPrompt.tsx": () => import("../components/mockups/notif-onboarding/NotifPrompt.tsx"),
  "./components/mockups/notif-onboarding/NotifSequence.tsx": () => import("../components/mockups/notif-onboarding/NotifSequence.tsx")
};
